services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: expressio-dev
    container_name: expressio-dev
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: sh -c "python manage.py runserver 0.0.0.0:8005"

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    

volumes:
  postgres-data:
