# Generated by Django 4.0 on 2021-12-30 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lastEdited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
