# Generated by Django 4.0 on 2021-12-30 17:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_lastedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='JPEG', keep_meta=True, null=True, quality=75, size=(720, 1280), upload_to='posts/thumbnails'),
        ),
    ]
