# Generated by Django 4.0 on 2022-01-01 07:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_profile/avatar/default_user_avatar.jpg', force_format='JPEG', keep_meta=True, quality=75, size=(360, 480), upload_to='user_profile/avatar'),
        ),
    ]
