# Generated by Django 4.0 on 2022-01-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
