# Generated by Django 4.0 on 2022-01-11 08:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='user_profile/avatar/default_user_avatar.jpg', force_format='JPEG', keep_meta=True, quality=75, size=(360, 360), upload_to='user_profile/avatar'),
        ),
    ]
