# Generated by Django 4.0 on 2022-01-13 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='claps',
        ),
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.ManyToManyField(null=True, related_name='post_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
