# Generated by Django 4.0 on 2022-01-15 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_remove_post_claps_post_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.ManyToManyField(related_name='post_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
