# Generated by Django 4.0 on 2022-01-17 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_profile_followers_profile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='user_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
