# Generated by Django 4.0 on 2022-01-19 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_profile_followers_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='post_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='post_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
