# Generated by Django 4.1 on 2022-10-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
