# Generated by Django 4.1 on 2022-11-24 17:26

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_post_description'),

    ]

    operations = [
        TrigramExtension(),
    ]


